# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'time2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for time2
  pod 'Firebase/Core'
  pod 'Firebase/Database'

  target 'time2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'time2UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
